### ISSUE TITLE
Avoid conflicts when adding changelog entries

### ISSUE THREAD

**Issue by qsantos** [kraken-build/kraken#137]
Currently, adding a changelog entry is done by appending a TOML section to `kraken-build/.changelog/_unreleased.toml`. However, this directly leads to merge conflict when MRs are opened concurrently.

This can be partially mitigated by inserting the new changelog entry at a random point in the file, instead of appending to the end. However, this is only possible when the file already contains multiple entries, and the probability of conflict is still high.

A more robust solution would be to have a `_unreleased/` directory instead, and creating a new file for each entry. The file name could be either be chosen arbitrarily by the contributor (with a non-negligible chance of collision), or use the UUID from the `id` field. The files could then be optionally sorted, and merged together for a new release.

**Comment by qsantos** [comment]
@NiklasRosenstein Should this issue be reopened in https://github.com/NiklasRosenstein/slap?

**Comment by NiklasRosenstein** [comment]
You raise a good point, indeed this has caused some mild pain in the past. Yes, I think this would better live on Slap. :) Happy to transfer the issue.

Edit: Nvm, seems I can't transfer it across organization boundaries.

**Comment by qsantos** [comment]
Opened https://github.com/NiklasRosenstein/slap/issues/99 there!
